version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: